resources:
  - name: blah
    type: params
    versionTemplate:
      params:
        hello: world

  - name: simpleserver_repo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: slothbit/simpleserver
      versionName: master

  - name: jfrog-cli
    type: cliConfig
    integration: artifacts



jobs:
  - name: blahjob
    type: runSh
    steps:
      - IN: blah
      - IN: simpleserver_repo
      - IN: jfrog-cli
      - TASK:
          script:
            - echo "Hello world -- $hello"
