resources:
  - name: blah
    type: params
    versionTemplate:
      params:
        hello: world

  - name: simpleserver_repo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: slothbit/simpleserver
      versionName: master

  - name: jfrog-cli
    type: cliConfig
    integration: artifacts

  - name: pipe-hook
    type: webhook
    versionTemplate:
      webhookKey: Shippable!



jobs:
  - name: blahjob
    type: runSh
    steps:
      - IN: blah
      - IN: simpleserver_repo
      - IN: jfrog-cli
      - IN: pipe-hook
      - TASK:
          script:
            - echo "Hello world -- $hello"
            - pushd $SIMPLESERVER_REPO_STATE
            - ls -latr
            - npm install
            - ls -latr
            - popd
            - printenv | grep TRIGGERED
